- name: Install nginx
  become: yes
  apt:
    pkg:
    - nginx
    - certbot
    - python3-certbot-nginx

- name: Remove default nginx config
  become: yes
  file: name=/etc/nginx/sites-enabled/default state=absent

# - name: Install nginx site
#   become: yes
#   template:
#     src: templates/nonmatch.conf.j2
#     dest: /etc/nginx/sites-available/nonmatch.conf

# - name: Activate site
#   become: yes
#   file:
#     src: /etc/nginx/sites-available/nonmatch.conf
#     dest: /etc/nginx/sites-enabled/nonmatch.conf
#     state: link
#   notify: restart_nginx