- name: Create secret key
  copy:
    content: "{{ id_ed25519 }}"
    dest: "/home/{{ username }}/.ssh/id_ed25519"
    mode: 0600
- name: Create public key
  copy:
    content: "{{ id_ed25519_pub }}"
    dest: "/home/{{ username }}/.ssh/id_ed25519.pub"
    mode: 0644